package com.lzy.core


/**
 *  甲子相关的算法
 * Created by bukeyan on 2017/6/18.
 */
 class JiaZiAlgorithm {


     /**
      *
      *  六法冲克-细批终身详解 P616 论“大凶”
      *  “六法冲克”断生死关口 http://blog.sina.com.cn/s/blog_49d801fd0102dsp3.html
      *  key-60甲子是流年
      *  1。纳音隔一相克。用法：key：为流年，value：日柱
      *  2。纳音墓鬼相克。用法：key：为流年，value：日柱
      *  3。纳音空亡相克。用法：key：为流年，value：日柱
      *  4。拱夹生克
      *  5。井栏互克
      *  6。四角冲克，生死同途
      *  7。纳音同位克
      * [2017-08-03 add by longzhiyou]
      */
    static def mapJiaZiInfo=[
             "甲子":[
                     nayingeyike:"己亥",
                     nayinmuguike:"",
                     nayinkongwangke:["庚申","辛酉"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"戊子",
                             info:[]
                     ]
             ],
             "乙丑":[
                     nayingeyike:"壬子",
                     nayinmuguike:"癸丑",
                     nayinkongwangke:["庚申","辛酉"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"己丑",
                             info:[]
                     ]
             ],
             "丙寅":[
                     nayingeyike:"乙丑",
                     nayinmuguike:"",
                     nayinkongwangke:["庚戌","辛亥"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"",
                             info:[]
                     ]
             ],
             "丁卯":[
                     nayingeyike:"壬寅",
                     nayinmuguike:"",
                     nayinkongwangke:["庚戌","辛亥"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "戊辰":[
                     nayingeyike:"己卯",
                     nayinmuguike:"",
                     nayinkongwangke:["庚子","辛丑"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "己巳":[
                     nayingeyike:"丙辰",
                     nayinmuguike:"",
                     nayinkongwangke:["庚子","辛丑"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "庚午":[
                     nayingeyike:"癸巳",
                     nayinmuguike:"",
                     nayinkongwangke:["甲申","乙酉"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "辛未":[
                     nayingeyike:"丙午",
                     nayinmuguike:"丁未",
                     nayinkongwangke:["甲申","乙酉"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "壬申":[
                     nayingeyike:"癸未",
                     nayinmuguike:"",
                     nayinkongwangke:["壬午","癸未"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "癸酉":[
                     nayingeyike:"庚申",
                     nayinmuguike:"",
                     nayinkongwangke:["壬午","癸未"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "甲戌":[
                     nayingeyike:"癸酉",
                     nayinmuguike:"庚戌",
                     nayinkongwangke:["甲子","乙丑"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "乙亥":[
                     nayingeyike:"庚戌",
                     nayinmuguike:"",
                     nayinkongwangke:["甲子","乙丑"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "丙子":[
                     nayingeyike:"乙亥",
                     nayinmuguike:"",
                     nayinkongwangke:["戊午","己未"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]

             ],
             "丁丑":[
                     nayingeyike:"戊子",
                     nayinmuguike:"己丑",
                     nayinkongwangke:["戊午","己未"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "戊寅":[
                     nayingeyike:"丁丑",
                     nayinmuguike:"",
                     nayinkongwangke:["丙午","丁未"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "己卯":[
                     nayingeyike:"甲寅",
                     nayinmuguike:"",
                     nayinkongwangke:["丙午","丁未"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "庚辰":[
                     nayingeyike:"辛卯",
                     nayinmuguike:"戊辰",
                     nayinkongwangke:["戊戌","己亥"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "辛巳":[
                     nayingeyike:"戊辰",
                     nayinmuguike:"",
                     nayinkongwangke:["戊戌","己亥"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "壬午":[
                     nayingeyike:"丁巳",
                     nayinmuguike:"",
                     nayinkongwangke:["丙戌","丁亥"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "癸未":[
                     nayingeyike:"庚午",
                     nayinmuguike:"辛未",
                     nayinkongwangke:["丙戌","丁亥"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "甲申":[
                     nayingeyike:"己未",
                     nayinmuguike:"",
                     nayinkongwangke:["甲戌","乙亥"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "乙酉":[
                     nayingeyike:"丙申",
                     nayinmuguike:"",
                     nayinkongwangke:["甲戌","乙亥"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "丙戌":[
                     nayingeyike:"乙酉",
                     nayinmuguike:"壬戌",
                     nayinkongwangke:["壬申","癸酉"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "丁亥":[
                     nayingeyike:"壬戌",
                     nayinmuguike:"",
                     nayinkongwangke:["壬申","癸酉"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "戊子":[
                     nayingeyike:"辛亥",
                     nayinmuguike:"",
                     nayinkongwangke:["甲午","乙未"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "己丑":[
                     nayingeyike:"甲子",
                     nayinmuguike:"乙丑",
                     nayinkongwangke:["甲午","乙未"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "庚寅":[
                     nayingeyike:"辛丑",
                     nayinmuguike:"",
                     nayinkongwangke:["戊申","己酉"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "辛卯":[
                     nayingeyike:"戊寅",
                     nayinmuguike:"",
                     nayinkongwangke:["戊申","己酉"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "壬辰":[
                     nayingeyike:"丁卯",
                     nayinmuguike:"甲辰",
                     nayinkongwangke:["丙申","丁酉"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "癸巳":[
                     nayingeyike:"甲辰",
                     nayinmuguike:"",
                     nayinkongwangke:["丙申","丁酉"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "甲午":[
                     nayingeyike:"己巳",
                     nayinmuguike:"",
                     nayinkongwangke:["庚寅","辛卯"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "乙未":[
                     nayingeyike:"壬午",
                     nayinmuguike:"癸未",
                     nayinkongwangke:["庚寅","辛卯"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "丙申":[
                     nayingeyike:"乙未",
                     nayinmuguike:"",
                     nayinkongwangke:["庚辰","辛巳"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "丁酉":[
                     nayingeyike:"壬申",
                     nayinmuguike:"",
                     nayinkongwangke:["庚辰","辛巳"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "戊戌":[
                     nayingeyike:"己酉",
                     nayinmuguike:"丙戌",
                     nayinkongwangke:["庚午","辛未"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "己亥":[
                     nayingeyike:"丙戌",
                     nayinmuguike:"",
                     nayinkongwangke:["庚午","辛未"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "庚子":[
                     nayingeyike:"癸亥",
                     nayinmuguike:"",
                     nayinkongwangke:["甲寅","乙卯"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "辛丑":[
                     nayingeyike:"丙子",
                     nayinmuguike:"丁丑",
                     nayinkongwangke:["甲寅","乙卯"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "壬寅":[
                     nayingeyike:"癸丑",
                     nayinmuguike:"",
                     nayinkongwangke:["壬子","癸丑"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "癸卯":[
                     nayingeyike:"庚寅",
                     nayinmuguike:"",
                     nayinkongwangke:["壬子","癸丑"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "甲辰":[
                     nayingeyike:"癸卯",
                     nayinmuguike:"庚辰",
                     nayinkongwangke:["甲午","乙未"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "乙巳":[
                     nayingeyike:"庚辰",
                     nayinmuguike:"",
                     nayinkongwangke:["甲午","乙未"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "丙午":[
                     nayingeyike:"乙巳",
                     nayinmuguike:"",
                     nayinkongwangke:["戊子","己丑"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "丁未":[
                     nayingeyike:"戊午",
                     nayinmuguike:"己未",
                     nayinkongwangke:["戊子","己丑"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "戊申":[
                     nayingeyike:"丁未",
                     nayinmuguike:"",
                     nayinkongwangke:["丙子","丁丑"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "己酉":[
                     nayingeyike:"甲申",
                     nayinmuguike:"",
                     nayinkongwangke:["丙子","丁丑"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "庚戌":[
                     nayingeyike:"辛酉",
                     nayinmuguike:"戊戌",
                     nayinkongwangke:["戊辰","己巳"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "辛亥":[
                     nayingeyike:"戊戌",
                     nayinmuguike:"",
                     nayinkongwangke:["戊辰","己巳"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "壬子":[
                     nayingeyike:"丁亥",
                     nayinmuguike:"",
                     nayinkongwangke:["丙辰","丁巳"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "癸丑":[
                     nayingeyike:"庚子",
                     nayinmuguike:"辛丑",
                     nayinkongwangke:["丙辰","丁巳"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "甲寅":[
                     nayingeyike:"己丑",
                     nayinmuguike:"",
                     nayinkongwangke:["甲辰","乙巳"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "乙卯":[
                     nayingeyike:"丙寅",
                     nayinmuguike:"",
                     nayinkongwangke:["甲辰","乙巳"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "丙辰":[
                     nayingeyike:"乙卯",
                     nayinmuguike:"壬辰",
                     nayinkongwangke:["丙子","丁丑"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "丁巳":[
                     nayingeyike:"壬辰",
                     nayinmuguike:"",
                     nayinkongwangke:["丙子","丁丑"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "戊午":[
                     nayingeyike:"辛巳",
                     nayinmuguike:"",
                     nayinkongwangke:["庚辰","辛巳"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "己未":[
                     nayingeyike:"甲午",
                     nayinmuguike:"乙未",
                     nayinkongwangke:["庚辰","辛巳"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "庚申":[
                     nayingeyike:"辛未",
                     nayinmuguike:"",
                     nayinkongwangke:["戊寅","己卯"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "辛酉":[
                     nayingeyike:"戊申",
                     nayinmuguike:"",
                     nayinkongwangke:["戊寅","己卯"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "壬戌":[
                     nayingeyike:"丁酉",
                     nayinmuguike:"甲戌",
                     nayinkongwangke:["丙寅","丁卯"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ],
             "癸亥":[
                     nayingeyike:"甲戌",
                     nayinmuguike:"",
                     nayinkongwangke:["丙寅","丁卯"],
                     gongjiake:[],
                     jinglanhuke:"",
                     sijiaochongke:[],
                     nayintongweike:[
                             match:"乙卯",
                             info:[]
                     ]
             ]
     ]


 }